### ISSUE TITLE
Purpose of this module?

### ISSUE THREAD

**Issue by NetOpWibby** [emailjs/emailjs-tcp-proxy#4]
I'm writing an email app right now and `emailjs` is awesome. I am also using Socket.io to make it feel realtime and I saw that this module also uses it. Forgive my ignorance, but I wanted to know more about how this module works.

There's no wiki, otherwise I'd look through that.

**Comment by felixhammerl** [comment]
No problem. This module tunnels TCP to socket.io transparently, without terminating the TLS traffic (which is done in the browser via [forge](https://github.com/digitalbazaar/forge)).
